### ISSUE TITLE
Allow multiple local configurations

### ISSUE THREAD

**Issue by pirm-in** [getdave/grunt-deployments#12] opened 2013-08-20 09:42 UTC
When working in a team, it would be nice to have the possibiltiy to setup multiple local configurations for each team meber. You could then maybe select the local database with another optional parameter.

**Comment by getdave** [comment] 2013-08-22 16:32
Thanks for taking the time to raise this issue.

I think this may be a duplicate of

https://github.com/getdave/grunt-deployments/issues/4

You can simply create a JSON file outside of VCS and then each team member can have their own "local".

Does this solve your problem? If so please let me know.

**Comment by getdave** [comment] 2013-09-20 09:16
No response. Closing.

**Closed as completed by getdave** 2013-09-20 09:16 UTC
